src/components/layout/index.scss
src/components/layout/index.tsx
src/components/layout/sidebar/index.tsx
src/components/layout/sidebar/navigation/index.tsx
src/components/screen/courses-screen/index.tsx
src/components/screen/courses-screen/style.module.css
src/components/screen/index.scss
src/components/screen/index.tsx
src/components/screen/style.module.css
src/components/screen/users-screen/index.tsx
src/constants/localization.ts
src/constants/mocks/courses-mock.ts
src/constants/mocks/users-mock.ts
src/constants/routes.ts

- Creating a general style.module to screen component (using screenClasses).
- Creating a mock data files for Users and Courses.
- Creating a localization file

Routing managements + mock data

---

src/components/common/WMButton/index.tsx
src/components/layout/header-toolbar/environment-menu/index.tsx
src/components/layout/header-toolbar/system-menu/index.tsx
src/components/layout/header-toolbar/user-menu/index.tsx

Also tweaked `WMButton` a little bit

Replace Button with WMButton

---

src/components/Screen/CoursesScreen/index.tsx
src/components/common/StatusDot/index.tsx
src/components/common/StatusDot/style.module.scss
src/components/common/WMTable/index.tsx
src/components/common/WMTable/style.module.scss
src/components/common/WMTag/index.tsx
src/components/common/WMTag/style.module.scss
src/components/common/tableCells/DashCell.tsx
src/components/common/tableCells/LinkCell.tsx
src/components/common/tableCells/NumberCell.tsx
src/components/common/tableCells/StatusDotCell.tsx
src/components/common/tableCells/SubtextCell.tsx
src/components/common/tableCells/TagCell.tsx
src/components/common/tableCells/TextArrayCell.tsx
src/components/common/tableCells/TextCell.tsx
src/components/common/tableCells/WarningCell.tsx
src/components/common/tableCells/style.module.scss
src/components/common/tableCells/tableCells.interface.ts
src/mocks/tableMockData.tsx
src/mocks/tableMockUsersData.tsx
src/styles/variables.scss

Styles table:
- Styles `WMTable`
- Adds cell components
- Updates mock data to use cell components

Style tables

---

src/components/Layout/Sidebar/NewCourseButton/index.tsx
src/components/Screen/CourseEditorScreen/index.tsx
src/components/Screen/EditorCourseScreen/index.tsx
src/components/Screen/index.tsx
src/constants/routes.ts

New route to course-editor

---

src/components/Screen/Playground/components/Dialogs.tsx
src/components/Screen/Playground/index.tsx
src/components/Screen/Playground/style.module.scss
src/components/Screen/index.tsx
src/components/common/WMConfirmationDialog/index.tsx
src/components/common/WMConfirmationDialog/style.module.scss
src/constants/routes.ts

- Adds playground screen (has path `/playground` but no link in nav)
- Has partial implementation of all system dialog

Playground Screen

---

src/components/common/WMPopover/index.tsx
src/components/common/WMPopover/style.module.scss

Updates `WMPopover` to include placement. Updates styling.

---

src/components/common/WMVerticalRadioGroup/style.module.scss
src/styles/variables.scss

Styles the `WMVerticalRadioGroup` according to [design](https://projects.invisionapp.com/d/main#/console/20017367/422589604/inspect)

Styles `WMVerticalRadioGroup`

---

.env
package-lock.json
package.json
src/App.tsx

Opens it when user clicks "ctrl+shift+up".

Adds "About TeachMe" dialog that holds the app version.

---

src/components/Screen/CourseEditorScreen/CourseOutline.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineTab.tsx
src/components/Screen/CourseEditorScreen/ResourcesList.tsx
src/components/Screen/CourseEditorScreen/index.tsx
src/components/Screen/CourseEditorScreen/style.module.scss
src/components/Screen/Playground/components/List.tsx
src/components/Screen/style.module.scss
src/components/common/EditableTitle/index.tsx
src/components/common/EditableTitle/style.module.scss
src/components/common/Icon/icon.interface.ts
src/components/common/Icon/iconsSVG.tsx
src/components/common/buttons/RefreshButton/index.tsx
src/components/common/lists/CourseItemsList/index.tsx
src/components/common/lists/CourseItemsList/style.module.scss
src/components/common/lists/CourseOutlineList/CourseOutlineLessonItem.tsx
src/components/common/lists/CourseOutlineList/index.tsx
src/components/common/lists/CourseOutlineList/style.module.scss
src/components/common/lists/index.ts
src/images/icons/lesson-small.svg
src/interfaces/course.interfaces.ts
src/providers/CourseEditorContext/actions.ts
src/providers/CourseEditorContext/course-editor-context.interface.ts
src/providers/CourseEditorContext/reducer.ts
src/providers/CourseEditorContext/utils.ts

- Split `CourseEditorScreen` to sub-components.
- Refactor `EditableTitle`, update its styles and fix its state update.
- Add new lesson to 'course outline' (WIP).
- Utilize course outline search filter.
- Refactor list components and update their styles.
- Update `CourseEditorScreen` provider.

Course editor lists

---

src/components/Layout/HeaderToolbar/style.module.scss
src/components/Layout/Sidebar/Navigation/style.module.scss
src/components/Layout/Sidebar/style.module.scss
src/components/Layout/style.module.scss
src/components/Screen/style.module.scss
src/components/common/WMDialog/style.module.scss
src/styles/variables.scss

- Add min-width for `Screen`.
- Rename some css vars.
- General style fixes.

Screen min-width of 1280px

---

src/components/Screen/CourseEditorScreen/index.tsx
src/components/common/EditableTitle/index.tsx
src/components/common/EditableTitle/style.module.scss

- Fixed focus on first load (when new).
- Added skeleton when loading.

Fix `EditableTitle` focus

---

src/components/Screen/CoursesScreen/index.tsx
src/components/Screen/CoursesScreen/tableData.tsx
src/components/Screen/index.tsx
src/components/common/tableCells/StatusDotCell.tsx
src/components/common/tableCells/tableCells.interface.ts
src/providers/CoursesContext/actions.ts
src/providers/CoursesContext/courses-context.interface.ts
src/providers/CoursesContext/index.tsx
src/providers/CoursesContext/reducer.ts
src/providers/CoursesContext/utils.ts

- Add `CoursesProvider`.
- Use SDK to render table data.
- Refactor table columns data.
TODO:
- Fix search filter.
- Utilize export table data.
- Clean up mock data.

Connect courses screen to sdk

---

package-lock.json
package.json
src/components/Layout/HeaderToolbar/index.tsx
src/components/Screen/CourseScreen/CourseScreenHeader.tsx
src/components/Screen/CourseScreen/index.tsx
src/components/Screen/CourseScreen/style.module.scss
src/components/Screen/CoursesScreen/index.tsx
src/components/Screen/UsersScreen/index.tsx
src/components/Screen/index.tsx
src/components/common/ScreenHeader/index.tsx
src/components/common/ScreenHeader/style.module.scss
src/components/common/filters/TimeFilter/index.tsx
src/components/common/filters/TimeFilter/style.module.scss
src/providers/CourseContext/actions.ts
src/providers/CourseContext/course-context.interface.ts
src/providers/CourseContext/index.tsx
src/providers/CourseContext/reducer.ts
src/providers/CourseContext/utils.ts
src/providers/CoursesContext/utils.ts

Created CourseProvider.
Removed course-screen mock-data.
Added to courseScreenHeader skeleton mode.
TODO: 
Remove mock data from quiz analytics section.
Integrate quiz tab analytics

Single course provider

---

package-lock.json
package.json
src/components/Screen/UsersScreen/LoadMoreWrapper.tsx
src/components/Screen/UsersScreen/ShownUsersIndicator.tsx
src/components/Screen/UsersScreen/index.tsx
src/components/Screen/UsersScreen/style.module.scss
src/components/common/WMButton/style.module.scss
src/components/common/buttons/LoadMoreButton/index.tsx
src/components/common/buttons/LoadMoreButton/style.module.scss
src/components/common/buttons/index.ts
src/components/common/filters/SearchFilter/index.tsx
src/components/common/filters/SearchFilter/style.module.scss
src/providers/UsersContext/index.tsx
src/providers/UsersContext/reducer.ts
src/providers/UsersContext/users-context.interface.ts
src/providers/UsersContext/utils.ts
src/styles/variables.scss
src/utils/index.ts

- Added 'Load More' button and utilize it (fetch 10 more users on each click). Also added users count indication.
- Integrated users search filter with SDK.
- Added debounce hook for search filter.
- Updated `SearchFilter` skeleton and styles.
- Updated `ShownUsersIndicator`: Fixed behavior and added skeleton.
- Updated empty users table styles.
- Tweaked courses screen 'create' button to have fixed width.

Users screen fetch update

---

src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/QuestionItem.tsx
src/components/Screen/CourseScreen/CourseTabs.tsx
src/components/Screen/CourseScreen/index.tsx
src/components/Screen/CoursesScreen/index.tsx
src/components/Screen/UsersScreen/index.tsx
src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
src/components/common/AnalyticsCharts/analytics.interface.ts
src/components/common/AnalyticsCharts/index.tsx
src/components/common/CourseQuizTabCharts/index.tsx
src/components/common/charts/WMHorizontalBarChart/index.tsx
src/constants/mocks/course-screen.ts

- Prepare QuizScoreChart component for working with the correct data from the SDK.
- Prepare CourseQuizTabCharts component for working with the correct data from the SDK - (set the data as empty as a temporary solution).
- Adding some todos.
TODO: 
Get a proper data and remove all comments
Canceling a Promise with useEffect in CoursesScreen & CourseScreen & UsersScreen

Single course analytics provider integration

---

src/components/Layout/HeaderToolbar/UserMenu.tsx
src/components/common/WMDropdown/index.tsx
src/providers/AppContext/actions.ts
src/providers/AppContext/app-context.interface.ts
src/providers/AppContext/reducer.ts
src/providers/AppContext/utils.ts
src/walkme/screens/general.ts

Impersonate button
To backoffice users only,
Impersonate button pop-up an Email dialog.

Impersonate button

---

src/components/Screen/CourseEditorScreen/CourseItemDetails/index.tsx
src/components/Screen/CourseEditorScreen/CourseItemsList/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineDetailsPanel/CourseOutlineDetailsPanel.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineDetailsPanel/style.module.scss
src/components/Screen/CourseEditorScreen/CourseOutlineLessonItem/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineLessonItem/style.module.scss
src/components/Screen/CourseEditorScreen/CourseOutlineList/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineList/style.module.scss
src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/CourseQuestionList.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/style.module.scss
src/components/Screen/CourseEditorScreen/CourseOutlineTab.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/Answers.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/QuestionScreenForm.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/QuizScreenForm.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/index.tsx
src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
src/components/Screen/CourseEditorScreen/QuizSettingsForm/index.tsx
src/components/Screen/Playground/components/QuizEdit.tsx
src/providers/CourseEditorContext/course-editor-context.interface.ts

- Uses settings components for all item types in the `CourseOutlineDetailsPanel`
- Makes changing settings mark state as having changes
- Adds pointer to all items that have settings

Course item settings

---

package-lock.json
package.json
src/components/Screen/CourseScreen/CourseOutlineTable.tsx
src/components/Screen/CourseScreen/CourseScreenHeader.tsx
src/components/Screen/CourseScreen/CourseTabs.tsx
src/components/Screen/CourseScreen/courseScreen.interface.ts
src/components/Screen/CourseScreen/index.tsx
src/components/Screen/CourseScreen/style.module.scss
src/components/Screen/CourseScreen/tableData.tsx
src/components/Screen/CourseScreen/utils.ts
src/components/common/AnalyticsCharts/CourseTimeCompletionChart/CourseTimeCompletionLegend.tsx
src/components/common/AnalyticsCharts/CourseTimeCompletionChart/index.tsx
src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
src/components/common/AnalyticsCharts/analytics.interface.ts
src/components/common/AnalyticsCharts/index.tsx
src/components/common/AnalyticsCharts/utils.ts
src/components/common/ControlsWrapper/style.module.scss
src/components/common/CourseQuizTabCharts/index.tsx
src/components/common/WMTable/WMTableExpanded.tsx
src/components/common/WMTable/index.tsx
src/components/common/WMTable/style.module.scss
src/components/common/charts/WMHorizontalBarChart/index.tsx
src/components/common/charts/WMHorizontalBarChart/style.module.scss
src/providers/CourseContext/actions.ts
src/providers/CourseContext/course-context.interface.ts
src/providers/CourseContext/reducer.ts
src/providers/CourseContext/utils.ts

- improve the data flow in AnalyticsChart child components.
- Adds properties to useCourseContext for courseOutline.
- changed call to SDK for getting correct data.
- Adds the logic for searching in courseOutline in useCourseContext.
- Updated version to 0.9.0
TODO:
- verify the data results with Eli.
- fix skeleton behavior

Single course outline integration

---

src/components/Screen/CourseEditorScreen/index.tsx
src/components/common/UnloadDialog/index.tsx
src/hooks/useEventListener.ts

And uses it in the build page so that when there are changes the user will be warned before leaving the page

Implements `UnloadDialog`

---

src/components/Screen/CourseEditorScreen/CourseOutlineList/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineList/style.module.scss
src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/style.module.scss
src/components/Screen/CourseEditorScreen/style.module.scss

- Fixes size of empty state when a quiz is added
- Fixes empty state button

Outline empty state fix

---

package.json
src/components/Layout/HeaderToolbar/SystemMenu.tsx
src/components/Screen/CoursesScreen/index.tsx
src/hooks/useRedirectToMain.ts
src/providers/AppContext/app-context.interface.ts
src/providers/AppContext/utils.ts

Declared system's type as a string to support non-system-users (the system returns an empty string).
Wrapped 'getSystems' with the condition to check if the system is valid as expected and try/catch

Support non system users

---

src/components/Screen/CourseScreen/CourseOutlineTable.tsx
src/components/Screen/CourseScreen/ExportCourseButton.tsx
src/components/Screen/CoursesScreen/ExportCoursesButton.tsx
src/components/Screen/CoursesScreen/SearchCoursesFilter.tsx
src/components/Screen/CoursesScreen/index.tsx
src/components/Screen/UsersScreen/index.tsx
src/components/common/buttons/ExportButton/index.tsx
src/components/common/filters/SearchFilter/index.tsx

- Removes the export dialog until exporting to e-mail is available.
- Disables actions when loading and when there are no results to export.

Removes the export dialog. Disables export when appropriate

---

src/components/Layout/HeaderToolbar/utils.ts
src/components/Screen/CourseEditorScreen/CourseItemDetails/index.tsx
src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
src/components/Screen/CourseEditorScreen/QuizSettingsForm/index.tsx
src/components/Screen/CoursesScreen/index.tsx

- changed parseSystems value - Uses system displayName instead of name
- Changed completionOptions label text to 'Item is completed'
- Preparations for supporting in disabled/enabled quiz
- Removed the settings icon, clicking on quiz's header opens the settings panel

Feedback fixes

---

src/components/Screen/CourseScreen/ExportCourseButton.tsx
src/components/Screen/CourseScreen/index.tsx
src/components/Screen/CoursesScreen/DeleteCoursesButton.tsx
src/components/Screen/CoursesScreen/ExportCoursesButton.tsx
src/components/Screen/CoursesScreen/ProductionStatusActions.tsx
src/components/Screen/CoursesScreen/index.tsx
src/components/Screen/UsersScreen/LoadMoreWrapper.tsx
src/components/Screen/UsersScreen/index.tsx
src/providers/AppContext/actions.ts
src/providers/AppContext/app-context.interface.ts
src/providers/AppContext/reducer.ts
src/providers/CourseContext/actions.ts
src/providers/CourseContext/course-context.interface.ts
src/providers/CourseContext/reducer.ts
src/providers/CoursesContext/actions.ts
src/providers/CoursesContext/courses-context.interface.ts
src/providers/CoursesContext/reducer.ts
src/providers/UsersContext/actions.ts
src/providers/UsersContext/reducer.ts
src/providers/UsersContext/users-context.interface.ts

- Lift up 'dateRange' from local screens' state to app-state.
- Update app reducer to use `immer`.

Date range update

---

src/components/Screen/CourseScreen/utils.ts
src/walkme/data/courseOutline.ts
src/walkme/models/course/outline.ts
src/walkme/screens/course.ts

Indicate if dropoff is enabled

Fix drop off

---

src/components/Screen/CourseEditorScreen/CancelDialog/index.tsx
src/components/Screen/CourseEditorScreen/CancelDialog/style.module.scss
src/components/Screen/CourseEditorScreen/HeaderConfirmationButtons.tsx
src/components/Screen/CourseEditorScreen/LessonHeader/style.module.scss
src/styles/mixins.scss

- Makes "cancel" button discard changes instead of going to courses page.
- Changes "cancel" button to "back to course list" button if it's a new course.
- Adds `CancelDialog` that warns user when the click "cancel".

Updates cancel flow

---

src/components/Screen/CourseEditorScreen/HeaderConfirmationButtons.tsx
src/components/Screen/CourseEditorScreen/index.tsx
src/components/Screen/Playground/components/CourseItemDetailsPanel.tsx
src/components/Screen/Playground/components/QuizEdit.tsx
src/providers/CourseEditorContext/utils.ts

- When trying to access a course that does not exists - shows the user and error and redirects to courses page.
- Passes correct envId to `fetchCourse()`.

Redirect when course does not exist

---

src/walkme/data/courseMetadata.ts
src/walkme/data/services/item.ts
src/walkme/screens/users.ts

Add getCourseMetadata API

---

package-lock.json
src/components/common/EditableTitle/index.tsx

When editing course name on build page, can confirm with a "enter" click

Confirm course name with "enter" click

---

src/components/common/AnalyticsCharts/CourseSummaryChart/index.tsx
src/components/common/AnalyticsCharts/index.tsx

Changed tooltip text by adding courseId boolean

Graph tooltip text in overview page should not refer to *this* course

---

src/walkme/data/courseBuild/course/index.ts
src/walkme/data/courseBuild/defaults.ts
src/walkme/data/courseBuild/quiz/index.ts
src/walkme/data/courseBuild/quiz/question/index.ts
src/walkme/data/courseBuild/quiz/screen.ts

New quiz enabled
New question textg

Reset quiz on delete

---

src/providers/CourseContext/utils.ts
src/providers/CoursesContext/utils.ts
src/providers/UsersContext/utils.ts
src/walkme/data/courseBuild/index.ts

Don't refresh data on get course

Await parallely on apis

---

package.json
src/components/Screen/CourseEditorScreen/QuizHeader/DeleteQuizDialog.tsx
src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
src/components/Screen/CourseEditorScreen/QuizHeader/style.module.scss

Also bumps up the app version to 0.16.0

Adds Delete Quiz dialog

---

src/components/Screen/CourseScreen/ExportCourseButton.tsx
src/components/Screen/CoursesScreen/DeleteCoursesButton.tsx
src/components/Screen/UsersScreen/index.tsx

- Prevent deleting modified course (a modified course is a published course with changes that haven't been published yet)
- Makes users table show loader on export button while exporting
- Makes course outline table show loader on export button while exporting

Table actions fixes

---

src/components/Layout/Sidebar/style.module.scss
src/components/Screen/CourseScreen/CourseScreenHeader.tsx
src/components/Screen/CourseScreen/style.module.scss
src/components/Screen/CoursesScreen/style.module.scss
src/components/Screen/CoursesScreen/tableData.tsx
src/components/common/ScreenHeader/style.module.scss
src/components/common/WMPopover/style.module.scss
src/components/common/WMTable/style.module.scss
src/styles/index.scss

- Fixing segments tooltip in table
- support long segments in the single course screen with tooltip
- minor styles changes

Segments tooltip

---

package.json
src/components/Screen/CourseScreen/CourseOutlineTable.tsx
src/components/Screen/CourseScreen/CourseTabs.tsx
src/components/Screen/CourseScreen/courseScreen.interface.ts
src/components/Screen/CourseScreen/index.tsx
src/components/Screen/CourseScreen/style.module.scss
src/components/Screen/CourseScreen/tableData.tsx
src/providers/CourseContext/course-context.interface.ts
src/providers/CourseContext/reducer.ts
src/providers/CourseContext/utils.ts

- Changed courseOutline interface & types. 
- detect if 'dropOffEnabled', 
- if dropOffEnabled is false rendering next to drop-off title alert icon with tooltip

Drop off column alert icon

---

src/components/common/AnalyticsCharts/CourseTimeCompletionChart/index.tsx
src/components/common/AnalyticsCharts/QuizCompletionRateChart/index.tsx
src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
src/components/common/AnalyticsCharts/analytics.interface.ts
src/components/common/AnalyticsCharts/index.tsx
src/components/common/charts/PieBarChart/index.tsx
src/components/common/charts/PieBarSummary/index.tsx
src/utils/index.ts

- Creating 'isValidNumber' method in utils.
- Using isValidNumber for detecting if the data is valid otherwise rendering empty state

Fixing analytics components data - treat zeros as valid data

---

src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/style.module.scss
src/components/Screen/CourseEditorScreen/QuizHeader/style.module.scss
src/components/Screen/CourseEditorScreen/TaskItem/style.module.scss

- Fixes active items background color.
- Makes quiz header look active when it's active.

Fix active items

---

src/components/Screen/CourseScreen/index.tsx
src/components/Screen/CourseScreen/style.module.scss

Fixed with adding a wrapper `div` to `CourseScreen` so the styles would have proper specificity.

Screen header content alignment fix

---

src/App.tsx
src/components/Screen/ErrorScreen/index.tsx

Removed the prop error from ErrorScreen , and changed the default error message

Error screen message

---

package.json
src/components/Screen/CourseEditorScreen/CourseItemDetails/index.tsx
src/components/Screen/Playground/components/CourseItemDetailsPanel.tsx
src/components/common/WMRadio/WMVerticalRadioGroup.tsx
src/components/common/WMRadio/interface.ts
src/components/common/WMRadio/style.module.scss

Adding an option to render help icon with tooltip to show option's helpText
Updated version to 0.19.0

Course editor item settings description

---

src/components/Layout/HeaderToolbar/index.tsx
src/components/common/dialogs/ImpersonateDialog/style.module.scss

- Changed impersonate user's email.
- Tried to change impersonate placeholder font-size

Impersonate boomerang issue

---

package-lock.json
package.json
src/components/Screen/CoursesScreen/index.tsx
src/components/Screen/CoursesScreen/tableData.tsx
src/components/common/AnalyticsCharts/CourseSummaryChart/index.tsx
src/components/common/AnalyticsCharts/CourseTimeCompletionChart/index.tsx
src/components/common/AnalyticsCharts/QuizCompletionRateChart/index.tsx
src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
src/components/common/ScreenHeader/index.tsx
src/components/common/WMTable/index.tsx
src/components/common/WMTextarea/index.tsx

Optimizations using (mostly) this technique: https://stackoverflow.com/a/55730151

Table select rows

---

src/components/Screen/UsersScreen/FiltersToolbar/index.tsx
src/components/Screen/UsersScreen/LoadMoreWrapper.tsx
src/components/Screen/UsersScreen/ShownUsersIndicator.tsx
src/components/Screen/UsersScreen/index.tsx
src/components/common/buttons/ExportButton/index.tsx
src/components/common/filters/SearchFilter/index.tsx

- Wraps values and functions in `useMemo()` and `useCallback()`.
- Wraps components in `React.memo()`.
- Makes "smart" components "dumb" (leaves only the screen component as "smart").

Optimizes Users screen

---

src/components/Screen/CoursesScreen/DeleteCoursesButton.tsx
src/components/Screen/CoursesScreen/ExportCoursesButton.tsx
src/components/Screen/CoursesScreen/ProductionStatusActions.tsx
src/components/Screen/CoursesScreen/SearchCoursesFilter.tsx
src/components/Screen/CoursesScreen/ShownCoursesIndicator.tsx
src/components/Screen/CoursesScreen/index.tsx
src/components/common/AnalyticsCharts/index.tsx
src/components/common/WMTable/index.tsx

- Wraps values and functions in `useMemo()` and `useCallback()`.
- Wraps components in `React.memo()`.
- Makes "smart" components "dumb" (leaves only the screen component as "smart").

Further optimizations in Courses screen

---

src/components/Screen/CourseScreen/CourseOutlineTable.tsx
src/components/Screen/CourseScreen/CourseScreenHeader.tsx
src/components/Screen/CourseScreen/CourseTabs.tsx
src/components/Screen/CourseScreen/ExportCourseButton.tsx
src/components/Screen/CourseScreen/index.tsx

- Wraps values and functions in `useMemo()` and `useCallback()`.
- Wraps components in `React.memo()`.
- Makes "smart" components "dumb" (leaves only the screen component and tabs component as "smart").

Optimizes single Course screen

---

src/components/Screen/CourseEditorScreen/ActionMenu.tsx
src/components/Screen/CourseEditorScreen/CourseEditorHeader.tsx
src/components/Screen/CourseEditorScreen/CourseItemDetails/index.tsx
src/components/Screen/CourseEditorScreen/CourseItemsList/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutline.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineDetailsPanel.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineLessonItem/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineList/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineListEmptyState.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineTab.tsx
src/components/Screen/CourseEditorScreen/CourseSettingsTab/index.tsx
src/components/Screen/CourseEditorScreen/HeaderConfirmationButtons.tsx
src/components/Screen/CourseEditorScreen/LessonHeader/EditbaleLessonTitle.tsx
src/components/Screen/CourseEditorScreen/LessonHeader/LessonDeleteButton.tsx
src/components/Screen/CourseEditorScreen/LessonHeader/index.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/Answers.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/QuestionScreenForm.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/QuizScreenForm.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/index.tsx
src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
src/components/Screen/CourseEditorScreen/QuizSettingsForm/index.tsx
src/components/Screen/CourseEditorScreen/ResourcesList.tsx
src/components/Screen/CourseEditorScreen/TaskItem/index.tsx
src/components/Screen/CourseEditorScreen/index.tsx
src/components/Screen/Playground/components/QuizEdit.tsx
src/components/Screen/Playground/components/QuizSettings.tsx
src/providers/CourseEditorContext/course-editor-context.interface.ts

- Wraps some values and functions in useMemo() and useCallback().
- Wraps some components in React.memo().
- Makes "smart" components "dumb" (leaves only the screen component as "smart").
Before:
After:

Course editor optimizations

---

package-lock.json
package.json
src/components/Screen/CoursesScreen/index.tsx
src/components/Screen/CoursesScreen/style.module.scss
src/components/Screen/CoursesScreen/tableData.tsx

- Adding indication to partial rows selection
- Reset all selection when the user deselects rows
- On dragged-row state adding styles to checkbox-cell

Courses table selection bugs

---

package.json
src/components/Screen/CourseEditorScreen/ActionMenu.tsx
src/components/Screen/CourseEditorScreen/CourseItemDetails/index.tsx
src/components/Screen/CourseEditorScreen/CourseItemsList/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutline.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineDetailsPanel.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineLessonItem/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineList/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineListEmptyState.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/index.tsx
src/components/Screen/CourseEditorScreen/CourseOutlineTab.tsx
src/components/Screen/CourseEditorScreen/CourseSettingsTab/index.tsx
src/components/Screen/CourseEditorScreen/LessonHeader/EditbaleLessonTitle.tsx
src/components/Screen/CourseEditorScreen/LessonHeader/LessonDeleteButton.tsx
src/components/Screen/CourseEditorScreen/LessonHeader/index.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/Answers.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/QuestionScreenForm.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/QuizScreenForm.tsx
src/components/Screen/CourseEditorScreen/QuizEditForm/index.tsx
src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
src/components/Screen/CourseEditorScreen/QuizSettingsForm/index.tsx
src/components/Screen/CourseEditorScreen/ResourcesList.tsx
src/components/Screen/CourseEditorScreen/TaskItem/index.tsx
src/components/Screen/CourseEditorScreen/index.tsx
src/components/Screen/Playground/components/QuizEdit.tsx
src/components/Screen/Playground/components/QuizSettings.tsx
src/providers/CourseEditorContext/course-editor-context.interface.ts

This reverts commit d73608c67cc8e5bbf645e9edf4bb7f31f33f6420, reversing
changes made to 1b6cf952635f847e068334f8adea0014a71f36fa.
#	src/components/Screen/CourseEditorScreen/CourseEditorHeader.tsx
#	src/components/Screen/CourseEditorScreen/HeaderConfirmationButtons.tsx
#	src/components/Screen/CourseEditorScreen/index.tsx

Revert "Merge pull request #268 from WalkMe/course-editor-optimizations"

---

src/components/Screen/CoursesScreen/tableData.tsx
src/components/common/AnalyticsCharts/utils.ts

- Fixed `calculatePercentages` method conditional results
- Fixed `Avg. Quiz Score` - treat 0 as valid number

Fix quiz avg
